server:
  port: 9877

spring:
  data:
    mongodb:
      uri: mongodb://localhost:30005/comment-service-mongodb
  cloud:
    discovery:
      enabled: true
  application:
    name: comment-service
#  config:
#    import: optional:configserver:http://config-server:8888
  profiles:
    active: resilience4j

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.fedbon.commentservice.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

logging:
  level:
    root: INFO