services:
  comment-service-mongo:
    container_name: comment-service-mongodb
    image: mongo:latest
    ports:
      - 30005:27017
    restart: always
    command: mongod --bind_ip_all
  author-service-mongo:
    container_name: author-service-mongodb
    image: mongo:latest
    ports:
      - 30004:27017
    restart: always
    command: mongod --bind_ip_all
  book-service-mongo:
    container_name: book-service-mongodb
    image: mongo:latest
    ports:
      - 30003:27017
    restart: always
    command: mongod --bind_ip_all
  user-server-mongo:
    container_name: user-server-mongodb
    image: mongo:latest
    ports:
      - 30002:27017
    restart: always
    command: mongod --bind_ip_all

