server:
  port: 9876

spring:
  data:
    mongodb:
      uri: mongodb://localhost:30004/author-service-mongodb
  cloud:
    discovery:
      enabled: true
  application:
    name: author-service

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.fedbon.authorservice.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

logging:
  level:
    root: INFO