server:
  port: 8765

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
  application:
    name: spring-gateway-service
  #  config:
  #    import: optional:configserver:http://config-service:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/v1/books/**
          filters:
            - AuthFilter
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/api/v1/auth/**

logging:
  level:
    root: DEBUG