server:
  port: 8765

spring:
  data:
    mongodb:
      uri: mongodb://localhost:30003/book-service-mongodb
  cloud:
    discovery:
      enabled: true
  application:
    name: book-service
  profiles:
    active: resilience4j

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.fedbon.bookservice.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

logging:
  level:
    root: INFO