server:
  port: 8083

spring:
  cloud:
    discovery:
      enabled: true
  application:
    name: security-service
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5430/fedbon
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5430/fedbon
    locations: classpath:db/migration
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keylength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 3600
  issuer: fedbon

logging:
  level:
    root: INFO