server:
  port: 8761

spring:
  application:
    name: eureka-discovery-server

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false

logging:
  level:
    root: INFO