server:
  port: 8888

spring:
  main:
    web-application-type: reactive
  application:
    name: config-server
  cloud:
    config:
      server:
          git:
            uri: https://github.com/fedbon/config-repo.git
            search-paths: {application}