server:
  port: 9885

spring:
  data:
    mongodb:
      uri: mongodb://localhost:30006/vote-service-mongodb
  cloud:
    discovery:
      enabled: true
  application:
    name: vote-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

mongock:
  change-logs-scan-package: false
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

logging:
  level:
    root: INFO